# -*- coding: utf-8 -*-
"""BFS_LR1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KGtEYPAy0rspg_0F_IvNREWVunL0eQ-4
"""

import streamlit as st

# --- App Title ---
st.title("Breadth-First Search (BFS) Traversal")
st.write("This app performs BFS traversal on a directed graph (see image below).")

# --- Display the graph image ---
st.image("/content/LabReport_BSD2513_#1.jpg", caption="Directed Graph for BFS Traversal", use_column_width=True)

# --- Graph definition ---
graph = {
    'A': ['B', 'D'],
    'B': ['C', 'E', 'G'],
    'C': ['A'],
    'D': ['C'],
    'E': ['H'],
    'F': [],
    'G': ['F'],
    'H': ['F', 'G']
}

# --- BFS function ---
def bfs(graph, start):
    """
    Perform Breadth-First Search traversal on a directed graph.
    Args:
        graph (dict): Adjacency list of the graph
        start (str): Starting node
    Returns:
        list: Traversal order
    """
    visited = []
    queue = []
    traversal_order = []

    visited.append(start)
    queue.append(start)

    while queue:
        s = queue.pop(0)
        traversal_order.append(s)

        for neighbour in graph[s]:
            if neighbour not in visited:
                visited.append(neighbour)
                queue.append(neighbour)

    return traversal_order

# --- Streamlit interface ---
start_node = st.selectbox("Select a starting node:", list(graph.keys()), index=0)

if st.button("Run BFS Traversal"):
    result = bfs(graph, start_node)
    st.success(f"**BFS Traversal starting from '{start_node}':**")
    st.write(" → ".join(result))

    # --- Show traversal steps ---
    st.subheader("Traversal Steps")
    for i, node in enumerate(result, start=1):
        st.write(f"Step {i}: Visit **{node}**")

# --- Show graph structure ---
st.subheader("Graph Structure (Adjacency List)")
for node, neighbors in graph.items():
    st.write(f"**{node}** → {', '.join(neighbors) if neighbors else '(no neighbors)'}")

st.caption("Developed for Search Algorithms Lab - BFS Example")